# Generated by Django 4.2.5 on 2025-02-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random',
            fields=[
                ('random_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('random_course_name', models.CharField(max_length=100)),
                ('random_course_problems', models.TextField()),
            ],
        ),
    ]
