# Generated by Django 4.2.5 on 2025-02-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0004_random'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random_problem',
            fields=[
                ('random_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_problems', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Random',
        ),
    ]
